---
title: "Course Assessment"
date: "2025-03-21"
---

# Pre-examination requirement (Prüfungsvorleistung):

Every two weeks, in one of the courses, we will assign you a problem set (*Übungsblatt*). You will typically have at least one week to complete and submit your solutions. You can find the problem set as well as supplementary materials on Moodle.

Please [**submit your solutions on Moodle**](https://moodle2.uni-leipzig.de/course/view.php?id=53760) as a rendered PDF or HTML file, generated using either Markdown or Quarto.



+--------------+--------------+------------------------------+
| Week         | Course       | Topics                       |
+==============+==============+==============================+
| 2            | CSS          | Social network analysis      |
+--------------+--------------+------------------------------+
| 5            | CSS          | Social network analysis      |
+--------------+--------------+------------------------------+
| 7            | ES           | Modeling Basics              |
+--------------+--------------+------------------------------+
| 9            | ES           | Diffusion Processes          |
+--------------+--------------+------------------------------+
| 11           | CSS          | Spatial data                 |
+--------------+--------------+------------------------------+
| 13           | ES           | tba                          |
+--------------+--------------+------------------------------+

# Course assessment (Prüfungsleistung)

At the end of the semester, you are expected to write a term paper (*Hausarbeit*), which will determine your final grade. Your paper will be evaluated as if it were a manuscript submitted to a scientific journal.

## General Information

-   **Length:** 4,500 words (± 10%, approximately 15 pages, excluding the title page, references, and tables)
-   **Formatting:**
    -   12 pt font size
    -   1.5 line spacing
    -   Justified text alignment
-   **Language:** German or English (American or British)
-   **Structure:** Write it like a scientific paper. Include an abstract, but [no table of contents]{.underline}. Ensure that your figures are informative and that tables are compact and free from redundancies.
-   **Tone:** Use precise and professional scientific language. Clearly motivate your work and place it within the context of existing literature.
-   **Deadline: TBA**

## Topic

You are essentially free to choose any topic that connects to one of our courses. However, keep in mind that different types of projects will naturally require different levels of effort for different parts of the term paper.

-   The more complex your **data acquisition** is, the less complex your **data analysis** can be. In theory, there could even be extreme cases where a very complex data acquisition process means that no data analysis is required (e.g., if the script runs for months scraping data that cannot be used before the end of the semester).

-   On the other hand, if you use an existing dataset (where data preparation is straightforward), we will expect a more in-depth and sophisticated statistical analysis.

In general: **talk to us** — we will help you determine whether your project is too ambitious or too simple, where to focus your effort, and how to balance the workload. Also, keep in mind that your term paper can be the foundation for a larger, more complex project (e.g., your master’s thesis).

+--------------------+------------------------------------------------------------------+
| Field              | Possible topics                                                  |
+====================+==================================================================+
| ES in general      | -   Write a detailed pre-registration plan for an experiment.    |
+--------------------+------------------------------------------------------------------+
| Agent-based models | -   Write a new, simple ABM.                                     |
|                    |                                                                  |
|                    | -   Reproduce and modify an existing ABM.                        |
|                    |                                                                  |
|                    | -   Examine an existing ABM in depth (e.g. sensitivity analysis) |
+--------------------+------------------------------------------------------------------+
| CSS in general     | -   Analyse existing data.                                       |
|                    |                                                                  |
|                    | -   Scrape or combine new datasets (and analyze them).           |
+--------------------+------------------------------------------------------------------+
| Networks           | -   Use existing network data and apply it to a new problem.     |
|                    |                                                                  |
|                    | -   Generate a new network dataset.                              |
+--------------------+------------------------------------------------------------------+
| Spatial data       | -   Use existing spatial data and apply it to a new problem.     |
|                    |                                                                  |
|                    | -   Generate a new spatial dataset.                              |
+--------------------+------------------------------------------------------------------+

# Use of AI for the problem sets and the term paper

If you chose to use AI-Applications for assignments that you hand in in this course, please document what and for what tasks you applied help. You can either do this by writing a statement of your own or you could also use AI-documentation tools like the [**AI-Usage-Cards**](https://ai-cards.org/) by the University of Göttingen.