project:
  type: website
  output-dir: docs

website:
  title: "CSS"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
          #- text: "Exercise Sheet 01"
          #  href: experimental-sociology/exercise-sheet-01.qmd
          #- text: "Exercise Sheet 02"
          #  href: experimental-sociology/exercise-sheet-02.qmd
          #- text: "Exercise Sheet 03"
          #  href: experimental-sociology/exercise-sheet-03.qmd #          - text: "Week 04"
        #            href: experimental-sociology/week04.qmd
        #          - text: "Week 05"
        #            href: experimental-sociology/week05.qmd
        #          - text: "Week 06"
        #            href: experimental-sociology/week06.qmd
        #          - text: "Week 07"
        #            href: experimental-sociology/week07.qmd
        #          - text: "Week 08"
        #            href: experimental-sociology/week08.qmd
        #          - text: "Week 09"
        #            href: experimental-sociology/week09.qmd
        #          - text: "Week 10"
        #            href: experimental-sociology/week10.qmd
        #          - text: "Week 11"
        #            href: experimental-sociology/week11.qmd
        #          - text: "Week 12"
        #            href: experimental-sociology/week12.qmd
        #          - text: "Week 13"
        #            href: experimental-sociology/week13.qmd
        #          - text: "Week 14"
        #            href: experimental-sociology/week14.qmd
      - text: "Class Materials"
        menu:
          - text: "Week 01 - Kick-off"
            href: computational-social-sciences/week01.qmd
          - text: "Week 02 - Networks I"
            href: computational-social-sciences/week02.qmd
          - text: "Week 03 - Networks II"
            href: computational-social-sciences/week03.qmd
          - text: "Week 04 - Networks III"
            href: computational-social-sciences/week04.qmd
          - text: "Week 05 - Spatial Analysis I"
            href: computational-social-sciences/week05.qmd
          - text: "Week 06 - Spatial Analysis II"
            href: computational-social-sciences/week06.qmd
          - text: "Week 07 - Text Analysis I (Bonus)"
            href: computational-social-sciences/week07.qmd
          #- text: "Week 08 - Text Analysis II"
          #  href: computational-social-sciences/week08.qmd
          - text: "Week 08 - Agent Based Modeling"
            href: computational-social-sciences/week08.qmd
          - text: "Week 09 - Open Science"
            href: computational-social-sciences/week09.qmd
      - text: "Course Assessment"
        menu:
          - text: "General Information"
            href: course-assessment/exam.qmd
          - text: "Exercise Sheet 01"
            href: course-assessment/exercise-sheet-01.qmd
          - text: "Exercise Sheet 01 - Solutions"
            href: course-assessment/exercise-sheet-01-solutions.qmd
          - text: "Exercise Sheet 02"
            href: course-assessment/exercise-sheet-02.qmd
          - text: "Exercise Sheet 02 - Solutions"
            href: course-assessment/exercise-sheet-02-solutions.qmd
          - text: "Exercise Sheet 03"
            href: course-assessment/exercise-sheet-03.qmd
          - text: "Exercise Sheet 03 - Solutions"
            href: course-assessment/exercise-sheet-03-solutions.qmd
          - text: "Assessment"
            href: course-assessment/assessment.qmd
      - text: "Further Resources"
        menu:
          - text: "Scientific Computing"
            href: general-information/sc.qmd
          - text: "Data Sources"
            href: general-information/data.qmd
          - text: "AI Usage"
            href: general-information/ai_usage.qmd
      - text: "Anti-Discrimination Policy"
        href: general-information/anti_dis.qmd
    

format:
  html:
    theme: cosmo
    title-block-banner: "#ecc3c8"
    css: styles.css
    html-math: katex
    code-fold: false
    code-tools: false
    highlight-style: github
    eval: false
    results: hide
    embed-resources: true
    self-contained-math: true
    bibliography-style: apa
    link-citation: true
    lightbox:
      loop: true
      match: auto
    include-in-header:
      - text: |
          <script type="text/javascript" src="/js/week-control.js"></script>

