---
title: "Computational Social Sciences"
subtitle: "Summer term 2026"

theme: cosmo
title-block-banner: "#ecc3c8"
---

# **Welcome to the computational social science (CSS) seminar!** {.unlisted}

This hands-on course explores how different data sources and computational methods can enhance our understanding of society. Using R, we will learn techniques for visualizing, analyzing and exploring large-scale data to gain deeper insights into social phenomena.

::: {.custom-block}

**General Information**

|              |                   |
|:-------------|-------------------|
| Wednesday    | 11:15 - 12:45     |
| GWZ, H2 1.15 | Start: 08.04.2026 |

:::


# 🔎 Focus

In these next weeks, we will have a closer look on these 3 key areas of CSS:

1.  **Social network analysis:** Understanding relationships and structures in network data, applying visualization techniques, and conducting empirical analyses.
2.  **Geo/Spatial data analysis:** Examining spatial patterns and dependencies, and leveraging location-based data for social science research.
3.  **Agent based modeling:** Simulating social processes and interactions using computational models to explore complex social dynamics.

# 🏁 Goals

We will combine different data sources and computational methods to combine theory-driven and data-driven approaches in social science research. By the end of the course, you will be able to:

-   Understand and apply key computational social science methods using R.
-   Analyze and visualize complex social data from various sources and
-   Critically evaluate the strengths and limitations of computational approaches in social science research.
    
    
# 🧩 Course structure

We’ll be following a **flipped classroom** strategy:

-   During the week, you’ll study the core concepts at your own pace — whether at home, in the library, or even in the park (it’s the summer term after all!).
-   At the beginning of each seminar, we’ll clear up any open questions before diving into **active problem-solving** and **programming**.
-   Expect a mix of hands-on coding, small-group discussions, and the occasional productive chaos when things don’t work as expected (that’s part of the learning process!).



# 🔧 Requirements

You don't really need any skills before we start, except for maybe some basic skills in R and definitely some curiosity and critical thinking. What we will need is a **laptop with R and RStudio installed and running**. If you don’t have a laptop, don’t hesitate to contact me -- we will work something out!



# 📆 Syllabus

| Week   | Date     | Subject                  | Content                                      | Readings                                                                                                                                                                                                      |
| ------ | -------- | ------------------------ | -------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **1**  | 08.04.26 | **Kick-off**             | - Introduction<br>- R Refresher              | Watts, D. J., & Lazer, D. (2025). Computational social science: Past, present, and future. In T. Yasseri (Hrsg.), *Handbook of Computational Social Science* (pp. 9–29). Edward Elgar Publishing.             |
| **2**  | 15.04.26 | *entfällt*               | -                                            | -                                                                                                                                                                                                             |
| **3**  | 22.04.26 | **Networks I**           | - Graph theory<br>- Network representations  | –                                                                                                                                                                                                             |
| **4**  | 29.04.26 | **Networks II**          | - Theoretical Insights<br>- Visualization    | Granovetter, M. S. (1973). The Strength of Weak Ties. American Journal of Sociology, 78, 1360–1380.                                                                                                           |
| **5**  | 06.05.26 | **Networks III**         | - Community detection<br>- Network inference | –                                                                                                                                                                                                             |
| **6**  | 13.05.26 | **Spatial analysis I**   | - Spatial thinking<br>- Visualizing space    | Logan, J. R. (2012). *Making a Place for Space: Spatial Thinking in Social Science*. Annual Review of Sociology, 38, 507–524.                                                                                 |
| **7**  | 20.05.26 | **Spatial analysis II**  | - Measuring distance<br>- Spatial inference  | –                                                                                                                                                                                                             |
| **8**  | 27.05.26 | **Agent-based modeling** | - Simulating social phenomena                | Lorenz, J. (2025). Exploring theory with agent-based modeling and simulation. In T. Yasseri (Hrsg.), Handbook of Computational Social Science (S. 236–257). Edward Elgar Publishing Limited.                  |
| **9**  | 03.06.26 | **Open science and CSS** | –                                            | Elmer, T. (2023). Computational social science is growing up: Why puberty consists of embracing measurement validation, theory development, and open science practices. *EPJ Data Science*, 12(1), Article 1. |
| **10** | 10.06.26 | *Term paper*             | - Idea pitch<br>- Feedback session           |                                                                                                                                                                                                               |



# 📚 Readings

As I said in the first introduction course the link to the *Speicherwolke* with the literature is here: [https://speicherwolke.uni-leipzig.de/index.php/s/sRf5GJGeXZGEi3B](https://speicherwolke.uni-leipzig.de/index.php/s/sRf5GJGeXZGEi3B). The Access is restricted through a password, that I will send to you by mail. If you have any problems, please let me know!


# ☎️ Contact information

**Leonie Steinbrinker**  
✉️ [leonie.steinbrinker@uni-leipzig.de](mailto:leonie.steinbrinker@uni-leipzig.de)  
🏢 GWZ, H2 1.15 <br/>
🕒 Office hours: spontaneous, after appointment

---

<small>Parts of the content for this course were created with the assistance of GitHub Copilot, ChatGPT, and ChatAI. Please note that while these tools have contributed to the development of the course materials, the final content and structure have been carefully curated and tailored by myself.</small>
